version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    command: nginx -g "daemon off;"
    environment:
    	- VUE_APP_API_BASE_URL=http://backend:8000
