version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000